add from_existing_graph to neo4j vector
langchain-ai/langchain pull request #11124
Opened 2023-09-27 16:49 UTC by tomasonjo

This PR adds the option to create a Neo4jvector instance from existing graph, which embeds existing text in the database and creates relevant indices.

Todo:

* [ ] Docs
* [ ] Tests

2023-09-27 20:54 UTC, jexp commented on libs/langchain/langchain/vectorstores/neo4j_vector.py
> +        text_node_properties: List[str],
should validate that the list is not empty

2023-09-27 20:55 UTC, jexp commented on libs/langchain/langchain/vectorstores/neo4j_vector.py
> +                " str + '\\n' + k + ':' + coalesce(node[k], '')) AS text, "
add a space after the colon

2023-09-27 20:57 UTC, jexp commented on libs/langchain/langchain/vectorstores/neo4j_vector.py
> +                f"MATCH (n:{node_label}) "
quote with backticks?

2023-09-27 20:59 UTC, jexp commented on libs/langchain/langchain/vectorstores/neo4j_vector.py
> +                "str='', k IN $props | str + '\\n' + k + ':' + n[k]) AS text "
coalesce(n[k]) see the retrieval query above, 
can we reuse the expression
space after colon

we can also filter the non-null ones?

2023-09-27 21:00 UTC, jexp commented on libs/langchain/langchain/vectorstores/neo4j_vector.py
> +                f"RETURN id(n) AS id, reduce("
elementId(n)

2023-09-27 21:01 UTC, jexp commented on libs/langchain/langchain/vectorstores/neo4j_vector.py
> +                f"MATCH (n:{node_label}) "
misses the `WHERE elementId(n) = row.id

2023-09-27 21:01 UTC, jexp commented on libs/langchain/langchain/vectorstores/neo4j_vector.py
> +                "YIELD node RETURN distinct 'done'",
RETURN count(*) is nicer

2023-09-27 21:02 UTC, jexp requested changes
LGTM added a few comments, the most important one is fixing the update query

2023-09-28 09:11 UTC, tomasonjo commented
Updated given the proposals by @jexp , and added tests and docs, so it should be good to go now.

2023-09-28 22:02 UTC, baskaryan commented
thanks @tomasonjo @jexp!

2023-09-28 22:02 UTC, merged