SQLDatabase async support
langchain-ai/langchain pull request #11939
Opened 2023-10-17 19:28 UTC by sudranga

Add support for async sql database (by utilizing sqlalchemy apis). Could do with some more tests. But, would like some comments while i add tests.

Sample usage with SQLDatabaseChain as follows:

#!/usr/bin/env python3
import gevent.monkey
gevent.monkey.patch_all()

import asyncio
import asyncio_gevent
asyncio.set_event_loop_policy(asyncio_gevent.EventLoopPolicy())
import langchain
langchain.verbose=True

from langchain.utilities import SQLDatabase
from langchain.llms import OpenAI
from langchain_experimental.sql import SQLDatabaseChain

async def say(what):
    cnt = 0
    while cnt < 5:
        print(what)
        await asyncio.sleep(1)
        cnt += 1
          
async def do_db():
    db = await SQLDatabase.from_uri_async("sqlite+aiosqlite:///Chinook.db")
    llm = OpenAI(temperature=0, verbose=True)
    db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
    await db_chain.arun("How many employees are there?")
             

async def main():
    task1 = asyncio.create_task(say("HELLO"))
    task2 = asyncio.create_task(do_db())
    asyncio.gather(task1, task2)
    
asyncio.run(main())

2023-11-06 16:40 UTC, sudranga commented
@eyurtsev Any comments on the PR?

2024-07-11 14:44 UTC, eyurtsev commented
@sudranga Apologies for taking so long to get back to you. 

If you're interested in pursuing this, feel free to rebase from new master (code has moved to community), I'll help to take care of the review, but we'll need an implementation that does not depend on nest_asyncio.

I'm going to close for now since the PR, but if you're pursuing this feel free to open a new PR

2024-07-11 14:44 UTC, closed without merging

2024-07-11 14:44 UTC, eyurtsev requested changes

2024-07-11 14:44 UTC, eyurtsev commented on libs/langchain/langchain/utilities/sql_database.py
> +                nest_asyncio.apply()
We don't want an implementation that relies on nest_asyncio as its deprecated and involves monkey patching the asyncio library which isn't something we'd want to happen for folks in production code.