Retriever with score  #11062
langchain-ai/langchain pull request #12102
Opened 2023-10-21 11:57 UTC by vanamayaswanth

2023-10-21 11:58 UTC, vanamayaswanth commented
This PR will help to resolve the issue #11062  , please review and let me know

2023-10-21 12:09 UTC, sethusaim requested changes
Changes look good

2023-10-21 12:21 UTC, sethusaim approved these changes

2023-10-30 14:24 UTC, eyurtsev requested changes

2023-10-30 14:24 UTC, eyurtsev commented on libs/langchain/langchain/schema/vectorstore.py
> +        "similarity_score"
Let's not introduce a new search type for this purpose -- the names are too similar sounding and will be confusing; e.g., why does similarity_score return a score but not similarity_score_threshold?

Instead, let's add a parameter called `score_key: Optional[str] = None` If specified, it'll place a score when available in the metadata under the specified key. It sounds like this is only supported for now for `similarity_score_threshold` so we should document that clearly and raise a ValueError on an invalid parameter combination.

2023-10-31 10:29 UTC, sethusaim commented
One question what combinations should we allow the user to control ....for example - 
1. The user wants to filter based on the threshold - default option which is already there
2. The user wants to filter based on the threshold and wants the score of returned docs -  currently not sending any score
3. The user wants to get the scores of all the docs without threshold 

Also appending the score in metadata seemed like a better option since it can be treated as unique key like  
how we have for source, etc  [ which the user not explicity change ]. If the user does not want the "score" key, it is fine and he can choose to use it.
Ofcourse we can implement this without having a new search type

Attaching screenshot for point 2

![image](https://github.com/langchain-ai/langchain/assets/71321529/92766d38-03bc-43f7-a980-79685ffc7c6c)

2024-07-16 15:29 UTC, hwchase17 commented
were considering ways to do this in a more native way

2024-07-16 15:29 UTC, closed without merging