Added Nov 6th pricing changes for cheaper 3.5 and 4 models
langchain-ai/langchain pull request #12988
Opened 2023-11-07 09:18 UTC by newsbubbles

2023-11-07 17:51 UTC, mspronesti requested changes

2023-11-07 17:51 UTC, mspronesti commented on libs/langchain/langchain/callbacks/openai_info.py
> +    "gpt-4-1106-preview": 0.03,
this is missing the `"-completion"`, otherwise you are only overwriting the entry above.

2023-11-07 17:51 UTC, mspronesti commented on libs/langchain/langchain/callbacks/openai_info.py
> +    "gpt-3.5-turbo-1106": 0.002,
Same as above.

2023-12-06 04:04 UTC, hwchase17 commented on libs/langchain/langchain/callbacks/openai_info.py
> +    "gpt-4-1106-preview": 0.03,
```suggestion
    "gpt-4-1106-preview-completion": 0.03,
```

2023-12-06 04:04 UTC, hwchase17 commented on libs/langchain/langchain/callbacks/openai_info.py
> +    "gpt-3.5-turbo-1106": 0.002,
```suggestion
    "gpt-3.5-turbo-1106-completion": 0.002,
```

2023-12-06 04:05 UTC, hwchase17 approved these changes

2023-12-06 04:07 UTC, hwchase17 commented
i think this was already fixed in previous pr

2023-12-06 04:07 UTC, closed without merging