Fix langchain.llms OpenAI completion doesn't work due to v1 client update
langchain-ai/langchain pull request #13099
Opened 2023-11-09 00:21 UTC by dosuken123

This commit fixes the issue that langchain.llms OpenAI completion stopped working since the V1 openai client update.

Replace this entire comment with:
  - **Description:** This PR fixes the issue [AttributeError: module 'openai' has no attribute 'Completion'](https://github.com/langchain-ai/langchain/issues/12967) similar to https://github.com/langchain-ai/langchain/commit/8e0cb2eb84539b249198f98f7647a1f24b2392c2 and https://github.com/langchain-ai/langchain/issues/12967, 
  - **Issue:** https://github.com/langchain-ai/langchain/issues/12967,
  - **Dependencies:** `openai` v1.x.x client,
  - **Tag maintainer:** @baskaryan,
  - **Twitter handle:** @dosuken123 

Please make sure your PR is passing linting and testing before submitting. Run `make format`, `make lint` and `make test` to check this locally.

See contribution guidelines for more information on how to write/run tests, lint, etc: 
https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md

If you're adding a new integration, please include:
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/extras` directory.

If no one reviews your PR within a few days, please @-mention one of @baskaryan, @eyurtsev, @hwchase17.

2023-11-09 00:22 UTC, dosuken123 commented
This is the second attempt after I closed https://github.com/langchain-ai/langchain/pull/12973. 

This is similar fix with https://github.com/langchain-ai/langchain/commit/8e0cb2eb84539b249198f98f7647a1f24b2392c2 and https://github.com/langchain-ai/langchain/pull/12969.

2023-11-09 00:23 UTC, dosuken123 commented
Confirmed locally that it's working with the following script:

```
from langchain.llms import OpenAI

print(OpenAI().predict("Who's the president of the united states?"))
#=> The President of the United States is Joe Biden.
```

2023-11-09 01:08 UTC, dosuken123 commented
@baskaryan, @eyurtsev, @hwchase17 Would someone have time to review this PR that fixes langchain.llms OpenAI bug?

2023-11-09 04:56 UTC, lesong36 commented
@dosuken123 May I know which version of langchain and openai you are using?
I still have this issue for  llm and chatmodel is ok.

---
Name: langchain
Version: 0.0.332
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: /home/coty/miniconda3/envs/jupyter/lib/python3.11/site-packages
Requires: aiohttp, anyio, dataclasses-json, jsonpatch, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: jupyter_ai, jupyter_ai_magics, langchain-experimental, langserve
---
Name: openai
Version: 1.2.0
Summary: Client library for the openai API
Home-page: 
Author: 
Author-email: OpenAI <support@openai.com>
License: 
Location: /home/coty/miniconda3/envs/jupyter/lib/python3.11/site-packages
Requires: anyio, distro, httpx, pydantic, tqdm, typing-extensions
Required-by: guidance, jupyter_ai, pyautogen
---

`from langchain.chat_models import ChatOpenAI
from langchain.schema.messages import HumanMessage, SystemMessage
messages = [
    SystemMessage(content="You're a helpful assistant"),
    HumanMessage(content="Who's the president of the united states?"),
]
print(ChatOpenAI().invoke(messages).content)`

#As of my knowledge update in May 2021, the President of the United States is Joe Biden. He was inaugurated on January 20, 2021.

`from langchain.llms import OpenAI
print(OpenAI().invoke("Who's the president of the united states?"))`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 2
      1 from langchain.llms import OpenAI
----> 2 print(OpenAI().invoke("Who's the president of the united states?"))

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/base.py:229, in BaseLLM.invoke(self, input, config, stop, **kwargs)
    219 def invoke(
    220     self,
    221     input: LanguageModelInput,
   (...)
    225     **kwargs: Any,
    226 ) -> str:
    227     config = config or {}
    228     return (
--> 229         self.generate_prompt(
    230             [self._convert_input(input)],
    231             stop=stop,
    232             callbacks=config.get("callbacks"),
    233             tags=config.get("tags"),
    234             metadata=config.get("metadata"),
    235             run_name=config.get("run_name"),
    236             **kwargs,
    237         )
    238         .generations[0][0]
    239         .text
    240     )

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/base.py:507, in BaseLLM.generate_prompt(self, prompts, stop, callbacks, **kwargs)
    499 def generate_prompt(
    500     self,
    501     prompts: List[PromptValue],
   (...)
    504     **kwargs: Any,
    505 ) -> LLMResult:
    506     prompt_strings = [p.to_string() for p in prompts]
--> 507     return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/base.py:656, in BaseLLM.generate(self, prompts, stop, callbacks, tags, metadata, run_name, **kwargs)
    641         raise ValueError(
    642             "Asked to cache, but no cache found at `langchain.cache`."
    643         )
    644     run_managers = [
    645         callback_manager.on_llm_start(
    646             dumpd(self),
   (...)
    654         )
    655     ]
--> 656     output = self._generate_helper(
    657         prompts, stop, run_managers, bool(new_arg_supported), **kwargs
    658     )
    659     return output
    660 if len(missing_prompts) > 0:

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/base.py:544, in BaseLLM._generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    542     for run_manager in run_managers:
    543         run_manager.on_llm_error(e)
--> 544     raise e
    545 flattened_outputs = output.flatten()
    546 for manager, flattened_output in zip(run_managers, flattened_outputs):

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/base.py:531, in BaseLLM._generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    521 def _generate_helper(
    522     self,
    523     prompts: List[str],
   (...)
    527     **kwargs: Any,
    528 ) -> LLMResult:
    529     try:
    530         output = (
--> 531             self._generate(
    532                 prompts,
    533                 stop=stop,
    534                 # TODO: support multiple run managers
    535                 run_manager=run_managers[0] if run_managers else None,
    536                 **kwargs,
    537             )
    538             if new_arg_supported
    539             else self._generate(prompts, stop=stop)
    540         )
    541     except BaseException as e:
    542         for run_manager in run_managers:

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/openai.py:401, in BaseOpenAI._generate(self, prompts, stop, run_manager, **kwargs)
    389     choices.append(
    390         {
    391             "text": generation.text,
   (...)
    398         }
    399     )
    400 else:
--> 401     response = completion_with_retry(
    402         self, prompt=_prompts, run_manager=run_manager, **params
    403     )
    404     choices.extend(response["choices"])
    405     update_token_usage(_keys, response, token_usage)

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/openai.py:109, in completion_with_retry(llm, run_manager, **kwargs)
    103 def completion_with_retry(
    104     llm: Union[BaseOpenAI, OpenAIChat],
    105     run_manager: Optional[CallbackManagerForLLMRun] = None,
    106     **kwargs: Any,
    107 ) -> Any:
    108     """Use tenacity to retry the completion call."""
--> 109     retry_decorator = _create_retry_decorator(llm, run_manager=run_manager)
    111     @retry_decorator
    112     def _completion_with_retry(**kwargs: Any) -> Any:
    113         return llm.client.create(**kwargs)

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/openai.py:92, in _create_retry_decorator(llm, run_manager)
     83 def _create_retry_decorator(
     84     llm: Union[BaseOpenAI, OpenAIChat],
     85     run_manager: Optional[
     86         Union[AsyncCallbackManagerForLLMRun, CallbackManagerForLLMRun]
     87     ] = None,
     88 ) -> Callable[[Any], Any]:
     89     import openai
     91     errors = [
---> 92         openai.error.Timeout,
     93         openai.error.APIError,
     94         openai.error.APIConnectionError,
     95         openai.error.RateLimitError,
     96         openai.error.ServiceUnavailableError,
     97     ]
     98     return create_base_retry_decorator(
     99         error_types=errors, max_retries=llm.max_retries, run_manager=run_manager
    100     )

AttributeError: module 'openai' has no attribute 'error'

2023-11-09 16:34 UTC, BabellDev commented
@dosuken123 I am trying your fix and it doesn't seem to work for minor `openai` versions such as `1.0.0b3`.  This comparison is returning `False` in that case:
![image](https://github.com/langchain-ai/langchain/assets/136352541/692779f4-a1f7-4e33-aca7-a545976f0247)

I modified your fix to compare major version directly like so, and it seems to work:
```
def is_openai_v1() -> bool:
    _version = parse(version("openai"))
    return _version.major >= 1
```

2023-11-09 21:54 UTC, efriis reviewed
@baskaryan would love some eyes!

2023-11-09 21:54 UTC, efriis commented on libs/langchain/langchain/chat_models/openai.py
> +        if self.request_timeout is not None and not is_openai_v1():
think this was mistakenly removed in a previous pr

2023-11-09 21:54 UTC, efriis commented on libs/langchain/langchain/llms/openai.py
> +    async_client: Any  #: :meta private:
OpenAIChat isn't actually compatible with v1. Just updated some easy things in case someone adds in future. Deprecated class

2023-11-09 21:56 UTC, efriis commented
And thanks for getting this started @dosuken123 ! Added a few surrounding changes to make the compatibility match some of our other libs :)

2023-11-09 22:41 UTC, baskaryan commented on libs/langchain/langchain/llms/openai.py
> +    request_timeout: Union[float, Tuple[float, float], httpx.Timeout, None] = Field(
turns out httpx typing causes issues, can just type as Any. see #13154

2023-11-09 22:49 UTC, baskaryan approved these changes

2023-11-09 22:50 UTC, baskaryan requested changes
didn't mean to approve, should remove httpx typing. otherwise LGTM!

2023-11-09 23:11 UTC, baskaryan approved these changes

2023-11-09 23:12 UTC, merged

2023-11-10 01:24 UTC, dosuken123 commented
Thanks @baskaryan and @efriis ! LangChain is awesome!

2023-11-10 17:01 UTC, adazoulay commented
When can we expect the latest version of langchain to drop with these changes?

2023-11-10 19:14 UTC, efriis commented
@adazoulay 0.0.334 is out!