community(minor): prometheus metrics for token tracking callback
langchain-ai/langchain pull request #15726
Opened 2024-01-08 23:55 UTC by zzzming

Description:

Collect Token Tracking output for Prometheus metrics under the OpenAICallbackHandler. Prometheus metrics are crucial for modern monitoring and enterprise applications because they provide a powerful and flexible way to collect and aggregate real-time metrics about system performance and health. This enables organizations to proactively identify and address issues, ensuring high availability and reliability of their services.

It only collects metrics. It's still up to the application to expose them 

Here is an example how to expose metrics in user application. This is not part of this PR which only collects metrics.
```
from flask import Flask, Response, make_response

# Create the Flask App
app = Flask(__name__)

@app.route('/metrics')
def metrics():
    return Response(generate_latest(), mimetype=CONTENT_TYPE_LATEST)
```

Dependencies:
prometheus_client-0.19.0 is already specified under libs/community's poetry.

Twitter handle: itestmycode

@baskaryan, @eyurtsev, @hwchase17.

2024-01-09 08:30 UTC, nicoloboschi approved these changes

2024-01-11 15:39 UTC, zzzming commented
@baskaryan, @eyurtsev, @hwchase17 can you help review and merge this PR Thank you

2024-01-15 19:05 UTC, baskaryan commented on libs/community/langchain_community/callbacks/openai_info.py
> +from prometheus_client import Counter, Gauge
prometheus_client isn't a langchain-community required dependency so we should only import it within the functions that need it

2024-01-15 19:59 UTC, hinthornw requested changes
If the goal is to make an easy integration to send token counting metrics to prometheus, the way to do that is to make a separate prometheus callbackhandler that you provide whenever invoking an option. The OpenAI callback handler should NOT be required to have an awareness of prometheus.


You can do this by subclassing the `BaseCallbackHandler` (or somewhat more conveniently, the `Basetracer`)

2024-01-16 19:15 UTC, zzzming commented
@hinthornw as you suggested, I created a separate callback for Prometheus metrics. 
cc @baskaryan

2024-12-12 01:29 UTC, efriis commented
closing this one as stale / not passing CI. Happy to discuss if still active!

2024-12-12 01:29 UTC, closed without merging