langchain_community: Add MongoDB LLM Cache
langchain-ai/langchain pull request #17470
Opened 2024-02-13 18:17 UTC by Jibola

# Description
    - **Description:** Adding MongoDB LLM Caching Layer abstraction
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

Checklist:

- [x] PR title: Please title your PR "package: description", where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"
- [x] PR Message (above)
- [ ] Pass lint and test: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified to check that you're passing lint and testing. See contribution guidelines for more information on how to write/run tests, lint, etc: https://python.langchain.com/docs/contributing/
- [ ] Add tests and docs: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of @baskaryan, @efriis, @eyurtsev, @hwchase17.

2024-02-14 14:26 UTC, Jibola commented on libs/community/langchain_community/cache.py
> +
```suggestion
```

2024-02-14 14:26 UTC, Jibola commented on libs/community/langchain_community/vectorstores/mongodb_atlas.py
> +        pprint({k:v for k,v in params.items() if k != "queryVector"})
```suggestion
```

2024-02-15 19:47 UTC, Jibola commented
cc: @ShaneHarvey @blink1073

2024-02-15 20:39 UTC, ShaneHarvey requested changes

2024-02-15 21:15 UTC, Jibola commented
cc: @prakul

2024-02-15 21:19 UTC, Jibola commented on libs/community/langchain_community/cache.py
> +        wait_until_ready: Optional[bool] = None,
how about `ensure_indexed`?
or `wait_until_indexed`?

2024-02-15 22:51 UTC, blink1073 commented on libs/community/langchain_community/cache.py
> +        wait_until_ready: Optional[bool] = None,
I like `wait_until_indexed`

2024-02-16 04:19 UTC, efriis reviewed
Jib will move to partner package.

Some comments
- can we add some unit tests
- can we add docs to the caching page https://python.langchain.com/docs/modules/model_io/chat/chat_model_caching

2024-02-20 15:30 UTC, Jibola commented
> Jib will move to partner package.
> 
> Some comments
> 
> * can we add some unit tests
> * can we add docs to the caching page https://python.langchain.com/docs/modules/model_io/chat/chat_model_caching

Yeah, I've decided I'll move these changes to the partners/mongodb-atlas once the [partner-package PR is in ](https://github.com/langchain-ai/langchain/pull/17652).

2024-03-05 18:37 UTC, efriis approved these changes

2024-03-05 18:38 UTC, merged