langchain: enhance `LocalFileStore` to offer a `umask` parameter for shared `CacheBackedEmbeddings` caches
langchain-ai/langchain pull request #18077
Opened 2024-02-24 23:38 UTC by chrispy-snps

**Description:**
The `LocalFileStore` class can be used to create an on-disk `CacheBackedEmbeddings` cache. However, the default `umask` settings gives file/directory write perrmissions only to the original user. Once the cache directory is created, other users cannot write their own cache entries into the directory.

To make the cache usable by multiple users, this pull request updates the `LocalFileStore` constructor to accept a `umask` parameter that is used for file/directory creation. The `umask` value is applied to both file and directory creation.

For example, when configured with a `umask` of `0o007` (*user* and *group* permitted, *others* masked),

* Anyone in our group can contribute embeddings to the cache.
* If we implement cache cleanup/eviction in the future, anyone in our group can perform the cleanup.

The default is `umask=None`, which retains the original behavior of using the default `umask` settings.

**Issue:**
Implements enhancement #18075.

**Testing:**
I was unable to run unit tests; details in [this post](https://github.com/langchain-ai/langchain/discussions/15019#discussioncomment-8576684).

2024-02-28 19:37 UTC, eyurtsev commented on libs/langchain/langchain/storage/file_system.py
> +        orig_umask = os.umask(0)
This sets the umask globally as far as I understand which will create a dangerous race condition with the rest of the code base and a security vulnurability for any file write anywhere.

File storage cache is meant mostly for prototyping purposes and should be getting getting extra functionality like this (even if it were done without a race condition)

2024-02-28 19:37 UTC, eyurtsev requested changes
Introduces a security vulnerability due to a race condition

2024-02-28 19:38 UTC, eyurtsev commented
I don't think we want to accept enhancements to the LocalFileStore cache -- it's mostly there for prototyping purposes

2024-02-28 19:38 UTC, closed without merging

2024-03-03 23:58 UTC, chrispy-snps commented
@eyurtsev - thanks for pointing out the vulnerability with the global `umask` approach.

I understand that `LocalFileStore` is primarily a proof-of-concept, but it's 100% workable and sufficient in its own right. I can re-implement this feature using `chmod`. If you're open to that, let me know and I'd be happy to do it.

2024-03-07 01:51 UTC, eyurtsev commented
@chrispy-snps if it can be implemented without mutating any global state or increasing the complexity of understanding this implementation that's probably fine. The LocalFileStore is mostly meant as a reference implementation not actual production implementation.

Could you explain your use case a bit? Why use the local file system vs. say s3? Are you sharing the cache between multiple users in your organization?

2024-03-10 00:42 UTC, chrispy-snps commented
Superseded by #18857.