community: Implement lazy_load() for MHTMLLoader
langchain-ai/langchain pull request #18648
Opened 2024-03-06 10:29 UTC by cbornet

2024-03-06 18:06 UTC, eyurtsev requested changes

2024-03-06 21:56 UTC, cbornet commented on libs/community/langchain_community/document_loaders/mhtml.py
> +                    return
If we do that, the behavior will be slightly different than what exists currently (ie returning only the first part that is `text/html`. Is that OK ?

2024-03-07 16:49 UTC, eyurtsev commented on libs/community/langchain_community/document_loaders/mhtml.py
> +                    return
Oh my bad I think i didn't notice that this i what it was already doing

2024-03-07 16:50 UTC, eyurtsev approved these changes

2024-03-07 16:50 UTC, merged