community: Add Neptune Analytics support to NeptuneGraph
langchain-ai/langchain pull request #18934
Opened 2024-03-11 19:56 UTC by bechbd

**Description:** Add support for Neptune Analytics to the existing NeptuneGraph object
**Twitter handle:** @bechbd`

2024-03-12 05:48 UTC, baskaryan approved these changes

2024-03-13 05:55 UTC, 3coins requested changes
@bechbd 
Thanks for making these changes. I have added some comments to simplify some of the code. 
A high level comment, should we create a new class perhaps `NeptuneGraphAnalytics` to capture the analytics version? It seems like there are conflicting arguments for analytics vs graph and trying to fit everything into one class might be an overkill. Putting this in another class will also simplify the logic, getting rid of the if else blocks.

@krlawrence
What do you think about putting this in another class? We can abstract out some of the common code to avoid duplication. This is a one-way door, since we don’t want users to switch to a new class later on, so we should make this decision now.

2024-03-13 05:55 UTC, 3coins commented on libs/community/langchain_community/graphs/neptune_graph.py
> +        graphIdentifier: the graph identifier for a Neptune Analytics graph.  Ignored for Neptune Database
```suggestion
        graph_identifier: the graph identifier for a Neptune Analytics graph.  Ignored for Neptune Database
```

2024-03-13 05:55 UTC, 3coins commented on libs/community/langchain_community/graphs/neptune_graph.py
> +                    self.__isNeptuneAnalytics = True
Should we set this up at the beginning of the block? Also, the rest of the code is using snake case, let’s stick to that.
```python
self.use_analytics_api = service == “neptune-graph”
```

2024-03-13 05:55 UTC, 3coins commented on libs/community/langchain_community/graphs/neptune_graph.py
> +                        )
We can get rid of the nested block here by returning early.

```python
if service == "neptune-graph":
    self.graph_indentifier = graph_indentifier
    self.client = session.client(service, region_name=region_name)
    return

# remove the else, and continue with the rest of the code..
```

2024-03-13 05:55 UTC, 3coins commented on libs/community/langchain_community/graphs/neptune_graph.py
> +                    ) from e
Can simplify this.

```suggestion
                  version = “1.34.40” if service == “neptune_graph” else “1.28.38"                
                  raise ModuleNotFoundError(
                      f"NeptuneGraph requires a boto3 version {version} or greater.”
                      "Please install it with `pip install -U boto3`.”
                  ) from e
```

2024-03-13 05:55 UTC, 3coins commented on libs/community/langchain_community/graphs/neptune_graph.py
> +            else:
Else is extraneous here.

2024-03-13 05:55 UTC, 3coins commented on libs/community/langchain_community/graphs/neptune_graph.py
> +                )
```suggestion
            message = "Summary API error occurred on Neptune Analytics” if self.use_analytics_api else (
                "Summary API is not available for this instance of Neptune,”
                "ensure the engine version is >=1.2.1.0”
             ),
            raise NeptuneQueryException(
                {
                    "message": message,
                    "details": str(e),
                }
            ) 
```

2024-03-13 05:55 UTC, 3coins commented on libs/community/langchain_community/graphs/neptune_graph.py
> +                summary = response["payload"]["graphSummary"]
```suggestion
            summary = response["graphSummary”] if self.use_analytics_api else response["payload"]["graphSummary"]
```

2024-03-16 01:04 UTC, bechbd commented
Updated the code to split NeptuneGraph and NeptuneAnalyticsGraph into two separate classes, as it will simplify the maintenance.  I created an abstract base class, NeptuneBaseGraph to store the shared functionality between the two classes.  This did require an update of the NeptuneQAChain to check for the base class instead of the specific class.

2024-03-26 04:03 UTC, 3coins reviewed
@bechbd 
Great job on doing the refactoring. Left some suggestions about the base class. Also, I think we can put all classes within the same file `neptune_graph.py`, which will make imports simpler.

2024-03-26 17:45 UTC, bechbd commented
Thank you for the feedback @3coins , I've made the changes.

2024-03-26 20:09 UTC, 3coins commented
@bechbd 
Code looks good. Can you rebase and fix the CI errors.

2024-03-29 19:14 UTC, closed without merging