community: Added propagation of document metadata from O365BaseLoader
langchain-ai/langchain pull request #20663
Opened 2024-04-19 16:51 UTC by MacanPN

**Description:**
- Added propagation of document metadata from O365BaseLoader to FileSystemBlobLoader (O365BaseLoader uses FileSystemBlobLoader under the hood). 
  - This is done by passing dictionary `metadata_dict`: key=filename and value=dictionary containing document's metadata
- Modified `FileSystemBlobLoader` to accept the `metadata_dict`, use `mimetype` from it (if available) and pass metadata further into blob loader.

**Issue:**
- `O365BaseLoader` under the hood downloads documents to temp folder and then uses `FileSystemBlobLoader` on it.
- However metadata about the document in question is lost in this process. In particular:
  - `mime_type`: `FileSystemBlobLoader` guesses `mime_type` from the file extension, but that does not work 100% of the time. 
  - `web_url`: this is useful to keep around since in RAG LLM we might want to provide link to the source document. In order to work well with document parsers, we pass the `web_url` as `source` (`web_url` is ignored by parsers, `source` is preserved)

**Dependencies:**
None

**Twitter handle:**
@martintriska1

Please review @baskaryan

2024-04-30 16:51 UTC, MacanPN commented
@eyurtsev @baskaryan The PR is ready for review and merging! :)

2024-05-03 09:01 UTC, MacanPN commented
@eyurtsev @baskaryan Can you please provide me with a feedback and way to move forward with this PR? Thanks!

2024-05-09 15:36 UTC, petergoldstein commented
This PR is required for an internal deployment in a large enterprise environment.  We'd really like to see it merged.

Given that all checks pass, and the changes are relatively minor, what would help get it merged into an official version?  Any thoughts @hwchase17 ?

Happy to discuss the use case in more detail if that helps.  Thanks.

2024-05-14 07:15 UTC, MacanPN commented
!ping @eyurtsev @baskaryan @hwchase17

2024-05-15 13:01 UTC, eyurtsev requested changes

2024-05-15 13:01 UTC, eyurtsev commented on libs/community/langchain_community/document_loaders/blob_loaders/file_system.py
> +        metadata_dict: Optional[Dict[str, Dict[str, Any]]] = None,
This logic should be handled outside the file system blob loader. The code that is using the BlobLoader can inspect the the blobs and add metadata to them based on the path associated with them.

2024-05-20 13:12 UTC, MacanPN commented
@eyurtsev I've modified the PR to only work within base_o365 and sharepoint classes. Please take a look

2024-05-22 20:39 UTC, eyurtsev commented on libs/community/langchain_community/document_loaders/base_o365.py
> +            for document in loader.yield_blobs():
document != blob

```suggestion
            for blob in loader.yield_blobs():
```

2024-05-22 20:39 UTC, eyurtsev commented on libs/community/langchain_community/document_loaders/base_o365.py
> +                if document.path and hasattr(document.path, "name"):
Why is there a hasattr on document.path?  Blob.path is always defined.

2024-05-22 20:39 UTC, eyurtsev commented on libs/community/langchain_community/document_loaders/base_o365.py
> +                        metadata_dict[file.name]["source"] = file.web_url
A better way to write this to reduce code duplication:

```
metadata_dict[file.name] = {
    "source" : file.web_url,
    "mime_type" : file.mime_type,
    "created" : file.created,
    "modified" : file.modified,
    "created_by" : str(file.created_by),
    "modified_by" : str(file.modified_by),
    "description" : file.description,
}
```

2024-05-22 21:28 UTC, eyurtsev commented
@MacanPN going to push a few changes to your PR in a bit

2024-05-22 21:36 UTC, eyurtsev approved these changes

2024-05-22 21:36 UTC, eyurtsev commented
@MacanPN sorry for the delay, pushed some aesthetic changes through, let me know if looks good, if so i'll merge.

2024-05-23 08:57 UTC, MacanPN commented
@eyurtsev Changes look good. Thanks! I've now also resolved a conflict with `master`. Feel free to merge!
_Full speed ahead Mr. Spock :)_

2024-05-23 15:42 UTC, merged

2024-06-05 12:37 UTC, radvanyimome commented
Is this change included in the 0.2.2 releases?
I'm still getting

"ValueError: data=None mimetype=None encoding='utf-8' path=PosixPath('/tmp/tmprxucxkc7/filename.docx') metadata={} does not have a mimetype"