Added a function `from_existing_index` in `Qdrant` vector database.
langchain-ai/langchain pull request #20779
Opened 2024-04-23 08:18 UTC by spike-spiegel-21

Issue: #20514 
The current implementation of `construct_instance` expects a `texts: List[str]` that will call the embedding function. This might not be needed when we already have a client with collection and `path,  you don't want to add any text.

This PR adds a class method that returns a qdrant instance with an existing client.

Here everytime https://github.com/langchain-ai/langchain/blob/cb6e5e56c29477c6da5824c17f1b70af11352685/libs/community/langchain_community/vectorstores/qdrant.py#L1592 `construct_instance` is called, this line sends some text for embedding generation.

2024-04-23 08:26 UTC, spike-spiegel-21 commented
@hwchase17 @baskaryan Please check if it is relevant to add this function.

2024-04-24 21:01 UTC, baskaryan approved these changes
cc @kacperlukawski

2024-04-25 07:28 UTC, kacperlukawski commented
@Anush008 Could you please have a look?

2024-04-25 07:47 UTC, Anush008 commented on libs/community/langchain_community/vectorstores/qdrant.py
> +    def from_existing_index(
As per Qdrant's terminology,
```
from_existing_collection()
```
should be more appropriate.

2024-04-25 07:50 UTC, Anush008 commented on libs/community/langchain_community/vectorstores/qdrant.py
> +        path: str,
Why is `path` the only explicit param while the others are `**kwargs`?
I'd recommend specifying all the params supported by `_generate_clients()` explicitly for better typing.

2024-04-25 07:52 UTC, Anush008 requested changes
Suggested some QOL improvements.

2024-04-25 07:59 UTC, spike-spiegel-21 commented
@kacperlukawski @Anush008 thank you for suggesting improvements. I will do that.

2024-04-25 08:00 UTC, Anush008 commented on libs/community/tests/integration_tests/vectorstores/qdrant/test_from_existing_index.py
> +@pytest.mark.parametrize("collection_name", ["custom-collection"])
Can be a local variable instead.

2024-04-25 08:01 UTC, Anush008 commented on libs/community/tests/integration_tests/vectorstores/qdrant/test_from_existing_index.py
> +    """Test if the Qdrant.from_existing_client reuses the some client."""
```suggestion
    """Test if the Qdrant.from_existing_client reuses the same collection"""
```

2024-04-26 12:34 UTC, spike-spiegel-21 commented
@Anush008 Implemented all suggested improvements.

2024-04-26 12:37 UTC, Anush008 commented on libs/community/tests/integration_tests/vectorstores/qdrant/test_from_existing_collection.py
> +    """Test if the Qdrant.from_existing_collection reuses the same client."""
```suggestion
    """Test if the Qdrant.from_existing_collection reuses the same collection."""
```

2024-04-26 12:37 UTC, Anush008 commented on libs/community/langchain_community/vectorstores/qdrant.py
> +        Get instance of an existing Qdrant collection stored locally.
```suggestion
        Get instance of an existing Qdrant collection.
```

2024-04-26 12:57 UTC, Anush008 approved these changes
Thank you @spike-spiegel-21.

2024-04-26 22:34 UTC, merged