[partners/pinecone]: Add id_prefix as a parameter to PineconeVectorStore
langchain-ai/langchain pull request #22071
Opened 2024-05-23 16:10 UTC by cwaddingham

This change adds a new parameter, `id_prefix` when creating a PineconeVectorStore object. This allows the `list` operation to filter on ID prefixes and the option to delete all records with a common parent document. 

See the following Pinecone documentation entries for more details:

- [List all records with a common prefix](https://docs.pinecone.io/guides/data/list-record-ids#list-the-ids-of-records-with-a-common-prefix)
- [Delete all records with a common parent document](https://docs.pinecone.io/guides/data/manage-rag-documents#delete-all-records-for-a-parent-document)

2024-05-23 16:23 UTC, eyurtsev commented
I don't think we want to support this functionality. This is doable on the user side right now

2024-05-23 16:24 UTC, eyurtsev requested changes
I don't think this is a feature we want to add

2024-05-23 16:51 UTC, eyurtsev approved these changes

2024-07-01 20:45 UTC, efriis commented
Hey @cwaddingham is this something you still want merged? Looks like there have been some persistent CI issues if you could take a look at those and the merge conflicts, and reopen!

2024-07-01 20:45 UTC, closed without merging