agent: update agent root_validators
langchain-ai/langchain pull request #23256
Opened 2024-06-21 10:45 UTC by wenngong

Description: update agent Pydantic root_validators.
Issue: the issue #22819

2024-06-21 10:47 UTC, wenngong commented
@eyurtsev Please review, thx!

2024-06-21 14:43 UTC, eyurtsev requested changes
Hi @wenmengzhou thanks for the contribution!

Could you review the semantics of `pre=True`. When `pre=True`, the code *cannot* assume that any keys exist in `values` even ones that have default values. I pointed two places that will crash with a KeyError.

2024-06-21 15:36 UTC, wenngong commented
> Hi @wenmengzhou thanks for the contribution!
> 
> Could you review the semantics of `pre=True`. When `pre=True`, the code _cannot_ assume that any keys exist in `values` even ones that have default values. I pointed two places that will crash with a KeyError.

Hi @eyurtsev, thx for pointint out this issue, I will fix it!

2024-06-21 15:40 UTC, wenngong commented
@eyurtsev please review again, thanks!

2024-06-25 13:37 UTC, eyurtsev reviewed
@wenngong I'm going to push a few changes to this PR right now.

Thanks for the work! If you're doing more changes, could you keep a PR to no more than ~5 root validators. It'll help to get the PR reviewed and merged quickly!

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/agents/agent.py
> +    @root_validator(pre=False, skip_on_failure=True)
✅

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/agents/agent.py
> +    @root_validator(pre=False, skip_on_failure=True)
✅

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/agents/agent.py
> +    @root_validator(pre=False, skip_on_failure=True)
✅

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/agents/agent.py
> +    @root_validator(pre=False, skip_on_failure=True)
This one is better as `pre=True` since it's assigning a new value to `agent`

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/agents/openai_assistant/base.py
> +    @root_validator(pre=False, skip_on_failure=True)
✅

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/chains/router/llm_router.py
> +    @root_validator(pre=False, skip_on_failure=True)
✅

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/map_rerank.py
> +    @root_validator(pre=True)
pre=False, skip_on_failure=True

2024-06-25 13:37 UTC, eyurtsev commented on libs/langchain/langchain/chains/sequential.py
> +    @root_validator(pre=False, skip_on_failure=True)
:heavy_check_mark:

2024-06-25 13:50 UTC, eyurtsev approved these changes

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/map_reduce.py
> +    @root_validator(pre=False, skip_on_failure=True)
This needs to be pre=True

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/map_reduce.py
> +    @root_validator(pre=False, skip_on_failure=True)
This needs to be refactored to be pre=True

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/stuff.py
> +    @root_validator(pre=False, skip_on_failure=True)
it should be pre=True, and the logic needs to be updated

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/conversation/base.py
> +    @root_validator(pre=False, skip_on_failure=True)
great!

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/moderation.py
> +    @root_validator(pre=True)
great!

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/qa_with_sources/vector_db.py
> +    @root_validator(pre=True)
great

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/retrieval_qa/base.py
> +    @root_validator(pre=True)
great

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/retrieval_qa/base.py
> +    @root_validator(pre=True)
this works

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/conversation/base.py
> +    @root_validator(pre=False, skip_on_failure=True)
great

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/conversational_retrieval/base.py
> +    @root_validator(pre=True)
great

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/elasticsearch_database/base.py
> +    @root_validator(pre=False, skip_on_failure=True)
great

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/sequential.py
> +    @root_validator(pre=False, skip_on_failure=True)
Doesn't look correct, let's revert this one

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/conversation/base.py
> +    @root_validator(pre=False, skip_on_failure=True)
great

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/refine.py
> +    @root_validator(pre=False, skip_on_failure=True)
should be pre=True and logic needs to be updated

2024-06-25 13:50 UTC, eyurtsev commented on libs/langchain/langchain/chains/base.py
> +    @root_validator(pre=True)
great

2024-06-25 13:51 UTC, eyurtsev commented on libs/langchain/langchain/agents/agent.py
> +    @root_validator(pre=False, skip_on_failure=True)
```suggestion
    @root_validator(pre=True)
```

2024-06-25 13:53 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/map_reduce.py
> +    @root_validator(pre=False, skip_on_failure=True)
```suggestion
    @root_validator(pre=True)
```

2024-06-25 13:53 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/map_reduce.py
> +    @root_validator(pre=False, skip_on_failure=True)
```suggestion
    @root_validator(pre=True)
```

2024-06-25 13:53 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/map_rerank.py
> +    @root_validator(pre=True)
```suggestion
    @root_validator(pre=False, skip_on_failure=True)
```

2024-06-25 13:53 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/refine.py
> +    @root_validator(pre=False, skip_on_failure=True)
```suggestion
    @root_validator(pre=True)
```

2024-06-25 13:54 UTC, eyurtsev commented on libs/langchain/langchain/chains/combine_documents/stuff.py
> +    @root_validator(pre=False, skip_on_failure=True)
```suggestion
    @root_validator(pre=True)
```

2024-06-25 13:55 UTC, eyurtsev commented on libs/langchain/langchain/chains/sequential.py
> +    @root_validator(pre=False, skip_on_failure=True)
```suggestion
    @root_validator()
```

2024-06-25 14:26 UTC, wenngong commented
> @wenngong I'm going to push a few changes to this PR right now.
> 
> Thanks for the work! If you're doing more changes, could you keep a PR to no more than ~5 root validators. It'll help to get the PR reviewed and merged quickly!

@eyurtsev Thanks! I will follow your suggestion.

2024-06-26 13:33 UTC, wenngong commented
@ccurme we can merge this pr now, Thx!

2024-06-26 21:09 UTC, merged