Amended Spelling Errors
langchain-ai/langchain pull request #24726
Opened 2024-07-26 19:23 UTC by ENUMERA8OR

Amended minor spelling errors in various files in the codebase.

2024-07-28 18:38 UTC, ccurme requested changes

2024-07-28 18:38 UTC, ccurme commented on docs/docs/additional_resources/dependents.mdx
> +|[reworked/AgentGPT](https://github.com/reworkd/AgentGPT) | 27833 |
(here and in setup.mdx) `reworkd` is not a typo.

2024-07-28 18:38 UTC, ccurme commented on pyproject.toml
> -# aapply - async apply
this is not a typo

2024-07-28 18:38 UTC, ccurme commented on docs/docs/integrations/document_loaders/hugging_face_dataset.ipynb
> -       " Document(page_content=\"If only to avoid making this type of film in the future. This film is interesting as an experiment but tells no cogent story.<br /><br />One might feel virtuous for s
This is just rendering data in the HF `imdb` dataset, I wouldn't consider this a typo.

2024-07-28 18:38 UTC, ccurme commented on docs/scripts/tool_feat_table.py
> -        "langauges": "Python",
this key appears multiple times in this script.

2024-07-28 19:04 UTC, ENUMERA8OR commented
okay will change that.

2024-07-29 20:28 UTC, ENUMERA8OR commented
okay, will make the necessary changes.

2024-08-23 15:01 UTC, ccurme commented
Closing for now as I don't see any updates, let me know if I'm mistaken.

2024-08-23 15:01 UTC, closed without merging