Update tools.py
langchain-ai/langchain pull request #25377
Opened 2024-08-14 09:49 UTC by karthikcs

Explicitly return the dict, if not we get JSON parsing error

Thank you for contributing to LangChain!

- [ ] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

2024-08-14 13:58 UTC, eyurtsev requested changes
Hi @karthikcs,

Thanks for the change!

Could you add a unit test that shows what test case is fixed by this?

2024-08-14 13:58 UTC, eyurtsev commented
@baskaryan tagging you in case its obvious why this is needed

2024-08-14 14:33 UTC, karthikcs commented
@eyurtsev I was facing an issue mentioned in the https://github.com/langchain-ai/langchain/issues/24621 and the solution worked out for me was https://github.com/langchain-ai/langchain/issues/24621#issuecomment-2249409492. I think it should be merged so that root cause is resolved.

2024-08-16 13:23 UTC, karthikcs commented
> Hi @karthikcs,
> 
> Thanks for the change!
> 
> Could you add a unit test that shows what test case is fixed by this?

OK I will add a UT

2024-08-16 13:29 UTC, karthikcs commented
> Hi @karthikcs,
> 
> Thanks for the change!
> 
> Could you add a unit test that shows what test case is fixed by this?

@eyurtsev I have added a UT file. Please review and approve

2024-08-22 23:13 UTC, baskaryan commented
hi @karthikcs, i don't follow what the issue here is. what type other than dict or string are we trying to pass to tools, and why?

2024-08-28 03:00 UTC, hwchase17 commented
the unit test is not in the right format and I also dont realy understand the motivation. I would suggest opening an issue and we can proceed from there

2024-08-28 03:00 UTC, closed without merging

2024-09-09 17:49 UTC, karthikcs commented
> hi @karthikcs, i don't follow what the issue here is. what type other than dict or string are we trying to pass to tools, and why?

@baskaryan Sorry for delayed response. I am not explicitly passing anything to this function. I am instantiating PythonREPL tool and it is failing consistently. When I debug I found following 

FILE: langchain_openai/chat_models/base.py 
function `_lc_tool_call_to_openai_tool_call`
The parameter `tool_call["args"]` is causing the issue while converting the python code to JSON in the line 
`json.dumps(tool_call["args"]),`

When I debugged I found the value in `tool_call["args"]` was 

```
{'query': 'product = 889384 * 77734\nproduct', 'run_manager': <langchain_core.callbacks.manager.CallbackManagerForToolRun object at 0x000001CD53DBAA80>}
```

Expected value is only the code, without the `run_manager` element.

```
{'query': 'product = 889384 * 77734\nproduct'}
```

When I add `dict(tool_input)` in the function `_to_args_and_kwargs` in (langchain_core/tools/base.py) the unnecessary element `run_manager` is not added to `tool_calls`. So, please consider this suggestion.

2024-09-09 18:56 UTC, karthikcs commented
> hi @karthikcs, i don't follow what the issue here is. what type other than dict or string are we trying to pass to tools, and why?

Dear Harrison, is there any guide I can follow?