mongodb : update MongoDBChatMessageHistory to accept existing mongo_client
langchain-ai/langchain pull request #25726
Opened 2024-08-24 15:44 UTC by SuperMuel

### Description

This PR enhances the `MongoDBChatMessageHistory` class by adding support for initialization with an existing `MongoClient` instance.

#### Benefits:
- **Custom Configurations:** Allows the use of a `MongoClient` instance with specific configurations.
- **Performance Improvement:** Enhances performance by preventing the repeated creation of new `MongoClient` instances for each session, thereby eliminating the need for re-authentication on every new session.

#### Instantiation with a `connection_string` (current method):
```python
from langchain_mongodb import MongoDBChatMessageHistory

history = MongoDBChatMessageHistory(
    connection_string="mongodb://your-host:your-port/",
    session_id="your-session-id",
)
```

#### Instantiation with an existing `MongoClient` (new feature in this PR):
```python
from langchain_mongodb import MongoDBChatMessageHistory
from pymongo import MongoClient

existing_client = MongoClient("mongodb://your-host:your-port/")
history2 = MongoDBChatMessageHistory(
    connection_string=None,
    session_id="your-session-id",
    client=existing_client,
)
```

**Note:**  
Due to the existing parameter order where `connection_string` precedes `session_id`, and since `session_id` does not (and should not) have a default value, I think it’s not possible to set a default value of `None` for `connection_string`. Changing the order of these parameters would introduce breaking changes.

2024-08-28 08:10 UTC, baskaryan reviewed
cc @Jibola

2024-08-28 22:04 UTC, efriis commented on libs/partners/mongodb/langchain_mongodb/chat_message_histories.py
> +        mongo_client: Optional[MongoClient] = None,
```suggestion
        client: Optional[MongoClient] = None,
```

2024-08-28 22:04 UTC, efriis commented on libs/partners/mongodb/langchain_mongodb/chat_message_histories.py
> +            mongo_client: Optional[MongoClient]
```suggestion
            client: Optional[MongoClient]
```

2024-08-28 22:04 UTC, efriis commented on libs/partners/mongodb/langchain_mongodb/chat_message_histories.py
> +            )
```suggestion
        if client:
            if connection_string:
                raise ValueError("Must provide connection_string or client, not both")
            self.client = client
        elif connection_string:
            try:
                self.client = MongoClient(connection_string)
            except errors.ConnectionFailure as error:
                logger.error(error)
        else:
            raise ValueError(
                "Either connection_string or client must be provided"
            )
```

2024-08-28 22:05 UTC, efriis approved these changes

2024-08-29 13:31 UTC, Jibola requested changes
Overall, LGTM! Thanks for adding it!

Could you add a constructor test for it since it's introducing a new functionality?

2024-09-05 12:46 UTC, SuperMuel commented
I implemented some constructor tests, hope it's adequate :) @Jibola

2024-09-19 08:15 UTC, SuperMuel commented
Hey, I fix the lints in a few hours

2024-09-22 13:34 UTC, SuperMuel commented
@efriis Should be good :)

2024-09-25 16:31 UTC, haarisedhi102 commented
@SuperMuel nice work, looking forward to this change

2024-10-18 19:35 UTC, efriis commented
migrating this to the new partner repo in langchain-ai/langchain-mongodb - sorry for the delay!

2024-10-18 19:35 UTC, closed without merging