core: [env.py/get_from_env] change default value None -> sentinel object
langchain-ai/langchain pull request #26153
Opened 2024-09-06 16:28 UTC by morgandiverrez

**Description**
   Install sentinel value by default in get_from_env and get_from_dict_and_env function in env.py for let's None value by default and not raise ValueError in this case.

**Issue :**
[ [Partners-HuggingFace] Breaking Change - impossible to skip login after PR #23309 #26085](https://github.com/langchain-ai/langchain/issues/26085)

2024-09-06 17:05 UTC, eyurtsev reviewed
This may break a lot of static typing in dependent packages that assume that the return type can only be `str`. If you want to make the change you'll likely need to improve the type annotation behavior so that it captures the correct semantics

2024-09-06 17:47 UTC, morgandiverrez commented
I changed the code to only return a string as you asked. Do you think I can further improve this code?

2024-09-09 10:17 UTC, Benvii commented
Thanks @morgandiverrez , as mentionned in the issue :

> Introducing a sentinel value may be considered as a breaking change, get_from_env will then accept None as default value without raising any exception which is currently not accepted 🤔. This would assume that users rely on this exception being raised, which I my opinion shouldn't be considered as "nominal" usage of this method.

https://github.com/langchain-ai/langchain/issues/26085#issuecomment-2331968516

What do you think about this @eyurtsev ?

2024-09-09 10:17 UTC, Benvii approved these changes

2024-09-17 21:26 UTC, eyurtsev requested changes
Hi thanks for the update -- this still won't work for the type annotations.

Presumably we're changing the behavior to support a default=None type. When a user passes deafult=None, the return type should be Optional[str] rather than `str`.

The code can be updated using typing.overload (https://docs.python.org/3/library/typing.html#overload)

2024-09-30 20:30 UTC, eyurtsev commented
Moved to needs status since there was no activity on this.

Developers can use the existing `from_env` and `secret_from_env` in langchain_core.utils to get factories for this use case.

2024-10-08 20:02 UTC, eyurtsev commented
Closing the PR due to lack of activity. Will be happy to re-review if folks want to tackle and can get the type annotations working correctly.

2024-10-08 20:02 UTC, closed without merging