[Langchain]: On Chain Start Fix for `Chain` Class
langchain-ai/langchain pull request #26593
Opened 2024-09-17 21:40 UTC by keenborder786

- **Issue:** #26588

2024-09-17 21:41 UTC, keenborder786 commented
@eyurtsev please review

2024-09-17 22:05 UTC, eyurtsev requested changes
HI @keenborder786 this is not the correct fix. We removed the serialization representation on purpose. The tracer itself should be fixed to deal with no representation being passed

2024-09-17 22:06 UTC, eyurtsev commented
Here's some context: 
https://github.com/langchain-ai/langchain/pull/26270
https://github.com/langchain-ai/langchain/pull/26576

2024-09-17 22:06 UTC, eyurtsev commented
@keenborder786 we'll also need a unit test to be added for the PR to be merged

2024-09-18 15:34 UTC, keenborder786 commented
@eyurtsev okay understood, let me do it.

2024-09-20 00:33 UTC, keenborder786 commented
@eyurtsev review please

2024-09-22 22:20 UTC, keenborder786 commented
@eyurtsev I have implemented the changes

2024-09-23 19:25 UTC, eyurtsev approved these changes

2024-09-23 19:25 UTC, eyurtsev commented on libs/langchain/langchain/chains/base.py
> +            class_name=self.name,
This is a big decision! 

`on_chain_start` here is an event dispatcher. By updating the information sent here the code sets the shape of dispatched on chain start events.

i.e., we should probably not be including `class_name` and `lc_id` in here, instead everything can be placed in the `name` logic if any additional attributes are needed

2024-09-23 19:25 UTC, eyurtsev commented on libs/core/langchain_core/callbacks/stdout.py
> +        if "name" in kwargs:
We can fetch the `name`  from kwargs here if present and otherwise fallback to serialized representation

2024-09-23 19:26 UTC, eyurtsev commented on libs/langchain/langchain/chains/base.py
> +            class_name=self.name,
I'm going to remove these additions since they're not necessary or desirable

2024-09-23 19:28 UTC, eyurtsev commented
Should resolve: https://github.com/langchain-ai/langchain/issues/26773

2024-09-23 19:30 UTC, merged

2024-09-24 08:36 UTC, slyin87 commented
@eyurtsev sorry to ask, so which version should I use to have this fix in place? How do I figure out based on this PR?