Remove backticks from query executed by SQL Database Agent if they are there
langchain-ai/langchain pull request #26742
Opened 2024-09-21 13:42 UTC by iboates

**Description:** Fix a really trivial but wasteful problem with the SQL query generation refinement loop

**Issue:** Some LLMs have a really hard time with NOT putting markdown-style backticks around code blocks, no matter how hard you try to prompt it out of them. With ChatGPT 4o I was seeing it frequently get stuck in very long loops because of this, wasting precious tokens and also degrading the result as it hopelessly shuffled around the actual SQL (which was often actually correct!

This is really trivial to fix, just check the first and last few characters for the markdown backtick structure and get rid of it if it is there.

**Dependencies:** None

I don't have a twitter handle but a link to my Github would be nice!

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

2024-09-25 07:06 UTC, iboates commented
@baskaryan @efriis @eyurtsev @ccurme @vbarda @hwchase17 it said to ping you if nobody reviews the PR in a few days

2024-09-25 13:45 UTC, eyurtsev requested changes
This utility knows nothing about LLMs. I don't think it's reasonable to have any clean up code here for incorrect commands.

2024-09-25 14:01 UTC, iboates commented
> This utility knows nothing about LLMs. I don't think it's reasonable to have any clean up code here for incorrect commands.

Do you have a suggestion on where it would be better implemented?

2024-10-05 12:46 UTC, iboates commented
@eyurtsev This issue is still causing me quite a lot of grief, the only way I have been able to deal with it effectively is by using my own fork with the fix applied. I am really quite motivated to fix this more permanently, but I am not sure where would be a more appropriate place. The reason I put it where I did is because it is the "last stop" before anything gets executed on the database, so I can be guaranteed that it will be applied.

If you could tell me where would be a more appropriate place to put this, I am happy to do so.

2024-11-11 17:01 UTC, closed without merging