Enhance BM25SparseEmbedding initialization
langchain-ai/langchain pull request #26769
Opened 2024-09-23 10:06 UTC by FouadLbakali

- [ ] **PR title**: "Enhance BM25SparseEmbedding initialization"

- [ ] **PR message**:
    - **Description:** This update enhances the `BM25SparseEmbedding` class by allowing the initialization to optionally load a model from a specified path, in addition to fitting it with a provided corpus. This makes the embedding model more flexible for different use cases.
    - **Issue:** Not applicable

2024-09-25 13:30 UTC, eyurtsev requested changes
A few different bugs in this PR, left comments

2024-09-25 13:30 UTC, eyurtsev commented on libs/partners/milvus/langchain_milvus/utils/sparse.py
> +    def __init__(self, corpus: List[str] = None, path: str = None, language: str = "en"):
This is a breaking change use `*` to make and force it to be a last argument so that it's invoked by name.

2024-09-25 13:30 UTC, eyurtsev commented on libs/partners/milvus/langchain_milvus/utils/sparse.py
> +    def __init__(self, corpus: List[str] = None, path: str = None, language: str = "en"):
List type needs to be updated to an optional

2024-09-25 13:30 UTC, eyurtsev commented on libs/partners/milvus/langchain_milvus/utils/sparse.py
> +            self.bm25_ef.load(path)
Need to validate what happens if neither is provided or if both are provided

2024-11-07 02:36 UTC, efriis commented
You can find the integration package you would want to edit here: https://github.com/langchain-ai/langchain-milvus

sorry for the inconvenience!

2024-11-07 02:36 UTC, closed without merging