core[patch],langchain[patch],community[patch]: Bump version dependency of tenacity to >=8.1.0,!=8.4.0,<10
langchain-ai/langchain pull request #27201
Opened 2024-10-08 18:49 UTC by EricDiao

This should fixes the compatibility issue with graprag as in

- https://github.com/langchain-ai/langchain/discussions/25595

Here are the release notes for tenacity 9 (https://github.com/jd/tenacity/releases/tag/9.0.0)

2024-10-08 19:50 UTC, eyurtsev requested changes
Could you provide an upper pin everywhere? You can specify it like this:  `>=8.1.0,<10`

We're following semver for dependency specification.

It's generally better to have the library fail to install like here: https://github.com/langchain-ai/langchain/discussions/25595

than to fail at run time due to a subtle breaking change

2024-10-08 19:53 UTC, eyurtsev commented
Thanks @EricDiao , happy to merge but we need to maintain an upper bound (e.g., <10) to make sure.

If you're doing a bump in a library, it's good to review what the breaking change was. In this case, this looks safe  (https://github.com/jd/tenacity/releases/tag/9.0.0) -- this is good information to include with the PR

2024-10-08 20:32 UTC, eyurtsev commented on docs/docs/versions/v0_2/overview.mdx
> +    tenacity = ">=8.1.0"
```suggestion
    tenacity = "^8.1.0"
```

2024-10-08 20:37 UTC, eyurtsev approved these changes

2024-10-08 23:42 UTC, eyurtsev commented
Failing unit tests I'll investigate tomorrow

2024-10-08 23:46 UTC, EricDiao commented
I am also looking at reproduce the failed tests.

2024-10-09 00:14 UTC, EricDiao commented
@eyurtsev I merged changes on master back in https://github.com/langchain-ai/langchain/pull/27201/commits/538e8cb4252878e7f69abe8d99d7e162cfd2fcc4. It works now on my local testbed. You may want to trigger the CI again.

2024-10-09 13:48 UTC, eyurtsev commented
Thanks -- had to resolve merge conflicts on community, pushed an update

2024-10-09 14:00 UTC, merged