community: Resolve Pydantic AttributeError in document_loaders/youtube.py
langchain-ai/langchain pull request #27322
Opened 2024-10-13 20:07 UTC by TupleType

This error is thrown when upgrading to the latest langchain version:
```
if not values.get("credentials_path") and not values.get(
           ^^^^^^^^^^
AttributeError: 'pydantic_core._pydantic_core.ArgsKwargs' object has no attribute 'get'
```
I tested the fix locally

2024-10-27 13:27 UTC, TupleType commented
Hey @efriis, could you please review?

2024-10-29 15:30 UTC, eyurtsev commented
Hi @TupleType,

It's unclear to me what problem this PR addresses since no unit tests are included and no code to reproduce is included.

Ideally the solution doesn't involve Using ArgsKwargs -- we don't want to include too many special pydantic features as they increase the odds of bugs down the road and require developers to learn additional features.

2024-10-29 15:32 UTC, eyurtsev requested changes
Unclear what issue is being fixed. Need better example to reproduce ideally in the form of a unit test

2024-12-09 22:16 UTC, eyurtsev commented
Closing due to no activity @TupleType feel free to re-open if this is still needed!

2024-12-09 22:16 UTC, closed without merging