WIP Accelerte enabled open source models
langchain-ai/langchain pull request #410
Opened 2022-12-23 21:33 UTC by thepok

Many TODOs but already workable.

Now its easy to load big open source models.

I was able to load neox 20b and facebook 30b on my laptop with 64gb ram and 16gb vram.

2022-12-24 04:35 UTC, hwchase17 reviewed
nice! im not super familiar with accerlated stuff. how generic is the get_accelerated_gpt code?

2023-01-22 22:04 UTC, delip requested changes

2023-01-22 22:04 UTC, delip commented on langchain/llms/accelerate.py
> +        weights_path = "./accelerated_model_weights/" + model_name
Also, why is the weights path root hardcoded to current directory "."?

2023-01-22 22:04 UTC, delip commented on langchain/llms/accelerate.py
> +        if not os.path.exists(weights_path):
Doesn't huggingface automatically do this test when you call `from_pretrained`?

2023-01-22 22:04 UTC, delip commented on langchain/llms/accelerate.py
> +        config.use_cache = False
why disable HF cache use and create a new cache path manually as you are doing here?

2023-01-22 22:09 UTC, delip commented
> nice! im not super familiar with accerlated stuff. how generic is the get_accelerated_gpt code?

@hwchase17 Since I ran into similar issue and I am familiar with this, I left a bunch of comments to @thepok in a review. 

@thepok Besides the review comments, can you add an example of how Accelarate is used (preferably not as a notebook for review purposes)?

2023-01-23 07:46 UTC, thepok commented
@delip i have no interest at the moment to implement this further. Feel free to implement your suggestions or it could be possible to merge it in the huggingface llm loader

2023-05-15 21:57 UTC, dev2049 commented
stale

2023-05-16 10:22 UTC, closed without merging

2023-09-07 10:49 UTC, Bec-k commented
ugh, so this have not been integrated?

2023-09-07 18:12 UTC, thepok commented
nope, but i think huggingfaces transformer lib can it now by itself, and hugginfaces transformer is already in langchain :)