Add multi file patterns globbing for DirectoryLoader()
langchain-ai/langchain pull request #4847
Opened 2023-05-17 09:48 UTC by marcusyatim

# Add multi file patterns globbing for DirectoryLoader()

This PR replaces the old `glob` arg with a new arg `file_pattern: Optional[set] = None` that specifies the file pattern(s) you want to glob. E.g. `{".pdf"}` or `{".pdf", ".docx"}`, etc.

Or, if you want to load all files in the directory, can simply leave out the arg.

The globbing is done with Path.glob(), or Path.rglob(), as per before. The added algorithm allows for globbing to be done once, and not glob as many times as number of patterns. Resulting in fast performance.

@hwchase17 
@eyurtsev

2023-05-17 09:49 UTC, marcusyatim commented on langchain/document_loaders/directory.py
> +            # Add "." prefix in case user did not include it
Perhaps a good to have safety check? Because you never know if users types `pdf` instead of `.pdf`.

2023-05-17 09:52 UTC, marcusyatim commented on langchain/document_loaders/directory.py
> +            self.file_pattern = {
Technically can use a List too. The performance difference between sets and lists is generally negligible for small sizes. Probably only in the thousands would you then see sets being faster. And in our case, I don't imagine most use cases having thousands of file patterns.

But anyhoos, no reason not to use sets as well, no?

2023-05-17 15:45 UTC, eyurtsev requested changes

2023-08-11 21:54 UTC, baskaryan commented
stale

2023-08-11 21:54 UTC, closed without merging