Bug fixes in Redis - Vectorstore
langchain-ai/langchain pull request #4932
Opened 2023-05-18 15:05 UTC by iamadhee

# Bug fixes in Redis - Vectorstore (Removing dependencies of redisearch module in Redis module & few more code fixes)

Fixes  #3893 #4896

## Who can review?

@dev2049 @tylerhutcherson

2023-05-18 15:10 UTC, tylerhutcherson requested changes
Hey -- What is this fixing exactly? We need this redis module check here otherwise it will fail for folks running vanilla redis

2023-05-18 15:10 UTC, tylerhutcherson commented on langchain/vectorstores/redis.py
> -def _check_redis_module_exist(client: RedisType, required_modules: List[dict]) -> None:
This is not something we should remove. This checks for the existence of the required Redis extensions on the database side (RediSearch: https://redis.io/docs/stack/search).

2023-05-18 15:15 UTC, tylerhutcherson commented
> Hey -- What is this fixing exactly? We need this redis module check here otherwise it will fail for folks running vanilla redis

The confusion might be that there's Redis modules... RediSearch and RedisJSON for example (part of Redis Stack). These are what we use the code above to check for existence...

And then there's Python client libraries. The standard `redis` python library is all we need for langchain.

2023-05-18 15:26 UTC, iamadhee commented
I have reverted the previous code deletion and refined the error message @tylerhutcherson

2023-05-18 15:47 UTC, iamadhee commented
@nikhilkandur Please do `pip uninstall redisearch` and  do `pip install redis==4.5.5`
that'll solve the issue.

2023-05-18 15:48 UTC, tylerhutcherson commented
> Sorry about all the chaos. I'll revert the changes done to this error message. I'll just probably add the version of redis (>=4.1.0) that has to be installed by the user, in order to be compatible with langchain [here](https://github.com/hwchase17/langchain/blob/1ed4228822498fd58d33d377572af0821c496b20/langchain/vectorstores/redis.py#L129). Would that be fine?

Perfect. I think that will help a ton.

2023-05-18 15:53 UTC, nikhilkandur commented
I installed `redis==4.5.5` but i'm getting below error but that version of [redisearch](https://pypi.org/project/redisearch/#history) doesn't exists.

```sh
ValueError: Redis failed to connect: You must add the RediSearch (>= 2.4) module from Redis Stack. Please refer to Redis Stack docs: https://redis.io/docs/stack/
```

2023-05-18 16:12 UTC, tylerhutcherson commented
> @nikhilkandur Here's what:
> 
> The [Redisearch](https://pypi.org/project/redisearch/#history) standalone project is discontinued. We won't need the`redisearch` python package to be installed as it is already available bundled within the standard `redis>=4.1.0` package.
> 
> So, the error you get right now despite what the message suggests has nothing to do with redisearch (you can refer the previous conversations as well). I doubt it might have something to do with the redis connection itself. Please check on that front.


Exactly. The error you have @nikhilkandur is because you need to run the [Redis Stack docker container](https://redis.io/docs/stack/get-started/install/docker/) (or sign up for Redis Cloud) that bundles RediSearch functionality into the database. The Python client side is different. `redis>=4.1.0` is sufficient.

2023-05-18 16:24 UTC, nikhilkandur commented
> > @nikhilkandur Here's what:
> > The [Redisearch](https://pypi.org/project/redisearch/#history) standalone project is discontinued. We won't need the`redisearch` python package to be installed as it is already available bundled within the standard `redis>=4.1.0` package.
> > So, the error you get right now despite what the message suggests has nothing to do with redisearch (you can refer the previous conversations as well). I doubt it might have something to do with the redis connection itself. Please check on that front.
> 
> Exactly. The error you have @nikhilkandur is because you need to run the [Redis Stack docker container](https://redis.io/docs/stack/get-started/install/docker/) (or sign up for Redis Cloud) that bundles RediSearch functionality into the database. The Python client side is different. `redis>=4.1.0` is sufficient.

Currently, I'm making use of redis addon for heroku and using redis>=4.1.0 at the client side to make the vector store work. Isn't it sufficient ?

2023-05-18 16:40 UTC, tylerhutcherson commented
> > > @nikhilkandur Here's what:
> > > The [Redisearch](https://pypi.org/project/redisearch/#history) standalone project is discontinued. We won't need the`redisearch` python package to be installed as it is already available bundled within the standard `redis>=4.1.0` package.
> > > So, the error you get right now despite what the message suggests has nothing to do with redisearch (you can refer the previous conversations as well). I doubt it might have something to do with the redis connection itself. Please check on that front.
> > 
> > 
> > Exactly. The error you have @nikhilkandur is because you need to run the [Redis Stack docker container](https://redis.io/docs/stack/get-started/install/docker/) (or sign up for Redis Cloud) that bundles RediSearch functionality into the database. The Python client side is different. `redis>=4.1.0` is sufficient.
> 
> Currently, I'm making use of redis addon for heroku and using redis>=4.1.0 at the client side to make the vector store work. Isn't it sufficient ?

Sounds like Heroku's redis implementation does not include any of the add-on modules like RediSearch, RedisJSON, RedisGraph, etc. But to use Redis as a vector database, you need the RediSearch module...

2023-05-18 16:52 UTC, nikhilkandur commented
There seems like another bug, not sure if it is fixed recently in unreleased version. I'm seeing `kwargs` field inside kwargs. You can see it [here](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/redis.py#L406) while instantiation

```sh
  File ".../site-packages/redis/connection.py", line 956, in __init__
    super().__init__(**kwargs)
TypeError: AbstractConnection.__init__() got an unexpected keyword argument 'kwargs'
```

2023-05-18 16:53 UTC, tylerhutcherson commented
> There seems like another bug, not sure if it is fixed recently in unreleased version. I'm seeing `kwargs` field inside kwargs. You can see it [here](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/redis.py#L406) while instantiation
> 
> ```shell
>   File ".../site-packages/redis/connection.py", line 956, in __init__
>     super().__init__(**kwargs)
> TypeError: AbstractConnection.__init__() got an unexpected keyword argument 'kwargs'
> ```

yup fixing this

2023-05-18 16:59 UTC, tylerhutcherson commented
@iamadhee Can you change the name of this PR to be more specific to this fix and then will get this prioritized as well. Thanks!

2023-05-18 17:19 UTC, iamadhee commented
> @iamadhee Can you change the name of this PR to be more specific to this fix and then will get this prioritized as well. Thanks!

Have added the new title and description

2023-05-19 06:27 UTC, iamadhee commented
@tylerhutcherson updated the redisearch error message to avoid further confusions

2023-05-19 17:43 UTC, iamadhee commented
Is there anything else that is needed from my end on this PR? @tylerhutcherson

2023-05-19 17:56 UTC, tylerhutcherson commented on langchain/vectorstores/redis.py
> +        "to know more about installing redisearch"
```suggestion
        "to know more about installing the RediSearch module within Redis Stack."
```

2023-05-19 17:56 UTC, tylerhutcherson commented on langchain/vectorstores/redis.py
> +        "Redis cannot be used as a vector database without Redisearch"
```suggestion
        "Redis cannot be used as a vector database without RediSearch >=2.4"
```

2023-05-19 17:59 UTC, tylerhutcherson approved these changes
2 quick suggestions on wording. but yeah, LGTM!

cc @dev2049

2023-05-19 18:03 UTC, iamadhee commented
Made the suggested changes cc @tylerhutcherson @dev2049

2023-05-19 19:57 UTC, dev2049 commented
thanks @iamadhee!

2023-05-19 20:02 UTC, merged