Fix serialization issue with W&B
langchain-ai/langchain pull request #5693
Opened 2023-06-04 19:02 UTC by jjzhuo

The chain input_documents are not displaying properly in W&B, due to serialization issue:

<img width="1164" alt="Screenshot 2023-06-04 at 11 58 26 AM" src="https://github.com/hwchase17/langchain/assets/134809928/f31f14f6-0935-4cca-9913-6760cd40eadf">

2023-06-04 21:32 UTC, hwchase17 commented
@parambharat how does this look to you?

2023-06-05 03:33 UTC, parambharat commented
> The chain input_documents are not displaying properly in W&B, due to serialization issue:
> 
> <img alt="Screenshot 2023-06-04 at 11 58 26 AM" width="1164" src="https://user-images.githubusercontent.com/134809928/243201395-f31f14f6-0935-4cca-9913-6760cd40eadf.png">

Hi @jjzhuo , can you share an example of where you are seeing this ? A colab perhaps ?

2023-06-05 03:34 UTC, parambharat requested changes

2023-06-05 03:34 UTC, parambharat commented on langchain/callbacks/tracers/wandb.py
> +    base_span.results = [trace_tree.Result(inputs=serialize_inputs(run.inputs), outputs=run.outputs)]
@jjzhuo this should be `_serialized_inputs`

2023-06-05 04:18 UTC, jjzhuo commented
@parambharat The screenshot is from the [Weights and Biases](https://wandb.ai/) website.

You can reproduce it by adding a RetrievalQA in this notebook:
https://python.langchain.com/en/latest/integrations/agent_with_wandb_tracing.html

2023-06-05 05:52 UTC, parambharat commented
@jjzhuo , Thanks you for the fix. I have verified that the new `_serialize_inputs` method serializes the inputs of the `StuffDocumentsChain` in the following [wandb run](https://wandb.ai/parambharat/langchain-tracing/runs/sflt59a2?workspace=user-parambharat). 

@hwchase17 , This LGTM.

2023-06-05 05:53 UTC, parambharat approved these changes
LGTM

2023-06-08 02:44 UTC, hwchase17 approved these changes
thanks!

2023-06-08 03:44 UTC, merged