Update redis.py
langchain-ai/langchain pull request #6953
Opened 2023-06-30 03:14 UTC by akshayghatiki311

Provided an option to connect to redis cloud using password,port and db along with existing parameters

2023-09-11 17:52 UTC, Spartee requested changes
Change to kwargs.

2023-09-11 17:52 UTC, Spartee commented on langchain/memory/chat_message_histories/redis.py
> +        password: str | None=...,
This should just be ``**kwargs`` and passed to the ``Redis.from_url`` method as such. There are a number of other things a user might want to pass like TLS settings. Either way, the username, password, and port should always just be passed in the url ``redis://username:password@host:port``

2023-09-18 23:07 UTC, leo-gan commented
@akshayghatiki311 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

2023-11-07 03:50 UTC, efriis commented
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

2023-11-07 03:50 UTC, closed without merging