Add upserting capability to PGVector
langchain-ai/langchain pull request #7333
Opened 2023-07-07 09:31 UTC by angelol

Currently, the PGVector vectorstore only supports adding embeddings to the store. This PR adds upserting capability to the store, so you can update existing embeddings if the underlying text have changed. This is useful if you have indexed a set of documents but some of the documents are being changed and you want to keep the index up-to-date.

To use this feature, simply provided ids for all texts/or documents. The pgvector notebook has been updated accordingly.

The lack of upserting capability has been mention in issue #6866. 

👀  @rlancemartin, @eyurtsev

In case you want to announce on Twitter, my Twitter handle is @angelol

2023-09-18 23:15 UTC, leo-gan commented
@angelol Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

2023-10-30 14:42 UTC, eyurtsev requested changes

2023-10-30 14:42 UTC, eyurtsev commented on langchain/vectorstores/pgvector.py
> +                if should_upsert and id != last_seen_id:
This part is quite inefficient -- a network request per upsert

2023-10-30 14:42 UTC, eyurtsev commented on langchain/vectorstores/pgvector.py
> +    def delete_embeddings(self, ids: List[str]) -> None:
Not sure that deletion of embeddings should be supported. Likely a lot of things expect the embeddings to exist. An update in place / upsert should be sufficient instead

2023-11-07 03:46 UTC, efriis commented
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

2023-11-07 03:46 UTC, closed without merging