Enhance GraphQL Tool to accept Endpoint, Headers and Query Variables at the time of Query Execution
langchain-ai/langchain pull request #8616
Opened 2023-08-02 06:27 UTC by aditi-rajawat

2023-08-02 17:06 UTC, ramapalani commented
@aditi-rajawat Can you fix the failing unit test `poetry run pytest --disable-socket --allow-unix-socket tests/unit_tests/`?

2023-08-20 23:00 UTC, ramapalani commented
@eyurtsev Were you able to review this PR?  Let us know if you have any concerns with this PR.

2023-08-21 20:25 UTC, eyurtsev commented
Hi @aditi-rajawat apologies I missed the PR. Added to my review queue and hopefully will tackle tomorrow

2023-08-23 02:53 UTC, eyurtsev commented
Hi @aditi-rajawat thank you for the contribution! I left some comments on the PR, but the main thing I'd love to see is an explanation about the problems that this design solves and or real use cases for making this part dynamic. 

I'm unclear at the moment on whether the graphql tool even works (schema information isn't included as part of the LLM context if I'm not mistaken). 

This tool is associated with a notebook which should be updated to reflect the new code changes: https://python.langchain.com/docs/integrations/tools/graphql

2023-08-23 02:54 UTC, eyurtsev requested changes

2023-08-23 02:54 UTC, eyurtsev commented on libs/langchain/langchain/tools/graphql/tool.py
> +    headers: '{{"Authorization": "Bearer testtoken", "Accept": "application/json"}}'
Why is the LLM asked to output headers including auth? What's a good use case that explain in which situations we'd want the LLM to be able to fill in auth?

2023-08-23 02:54 UTC, eyurtsev commented on libs/langchain/langchain/utilities/graphql.py
> +from gql import Client
these are optional dependencies, so they should be tucked into optional imports , a user without `gql` installed should be able to import this file without getting any side effects

2023-08-23 02:54 UTC, eyurtsev commented on libs/langchain/langchain/utilities/graphql.py
> +    def get_gql_client(self, graphql_endpoint: Optional[str] = None, headers: Optional[Dict[str, str]] = None) -> Client:
this method and validate environment are duplicating client instantiation code

2023-08-23 02:54 UTC, eyurtsev commented on libs/langchain/langchain/tools/graphql/tool.py
> +
Could we trim the trailing whitespace -- since this is an input into an LLM

2023-08-23 02:54 UTC, eyurtsev commented on libs/langchain/langchain/tools/graphql/tool.py
> +            query: str,
nit: this is one level of indentation too deep

2023-08-23 02:54 UTC, eyurtsev commented on libs/langchain/langchain/tools/graphql/tool.py
> +            headers: Optional[Dict[str, str]] = None,
In general, we do not want the agent / LLM responsible for filling in information like headers which may have auth info

2023-09-20 17:34 UTC, leo-gan commented
@aditi-rajawat Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

2023-11-10 22:41 UTC, closed without merging

2023-11-10 22:41 UTC, efriis commented
Looks like this isn't being worked on anymore. I'll close for now, and if you resume work, feel free to reopen!