Move graphDB to integrations
langchain-ai/langchain pull request #8997
Opened 2023-08-09 19:51 UTC by rlancemartin

Clean `use_cases` by moving the `GraphDB` to `integrations`.

2023-08-09 19:58 UTC, eyurtsev commented
will colab paths update automatically?

2023-08-09 19:58 UTC, eyurtsev approved these changes

2023-08-09 23:03 UTC, baskaryan requested changes
these docs are all focused on the chains built around these graphs, and chains aren't integrations imo. if we wanna move i think we should update docs to make it clear the graph is the integration, and then show of the corresponding chain as a "how to use this" kinda section.

also tree of thought def shouldn't be integration

2023-08-11 23:05 UTC, rlancemartin commented
> move

Right. I like that: let's move these to `modules/chains/how_to/graph`. Looking more closely, I do see that these are largely (all?) chains derived from the GraphDB integrations, so it's sensible to do this. This is same as we can do for [self-check](https://github.com/langchain-ai/langchain/pull/9137) and [code writing](https://github.com/langchain-ai/langchain/pull/9134).

2023-08-15 00:07 UTC, baskaryan approved these changes

2023-08-15 00:20 UTC, merged