add ttl to RedisCache
langchain-ai/langchain pull request #9068
Opened 2023-08-10 18:34 UTC by glaucocustodio

Add `ttl` (time to live) to `RedisCache`

2023-08-10 19:43 UTC, eyurtsev commented on libs/langchain/langchain/cache.py
> +            self.redis.expire(key, self.ttl)
Are we able to do this using a pipeline to avoid an extra network request for setting the ttl?

2023-08-10 19:43 UTC, eyurtsev commented on libs/langchain/tests/integration_tests/cache/test_redis_cache.py
> +    time.sleep(1.1)
Let's not use sleep in unit tests -- it slows down tests when folks try to run them

Could we instead use 

```
https://redis.io/commands/ttl/
```
or
```
https://redis.io/commands/pttl/
```

To verify that the ttl associated with the key is more than 0?

2023-08-10 19:45 UTC, eyurtsev requested changes
@glaucocustodio  Thanks for the code contribution! I think it makes sense to add a ttl.

Requested a few minor changes, when you're ready could you request a re-review?

2023-08-13 10:47 UTC, glaucocustodio commented
hey @eyurtsev, thanks for the review, I've done the requested changes, could you please take a look again?

2023-08-14 16:58 UTC, eyurtsev approved these changes
Looks great!

2023-08-14 16:59 UTC, eyurtsev approved these changes

2023-08-14 16:59 UTC, eyurtsev commented on libs/langchain/langchain/cache.py
> +    def __init__(self, redis_: Any, *, ttl: Optional[int] = None):
nit:  https://google.github.io/styleguide/pyguide.html#383-functions-and-methods -- we follow google style for doc-strings

Parameters -> Args:

2023-08-14 16:59 UTC, merged