Master
langchain-ai/langchain pull request #9497
Opened 2023-08-19 19:52 UTC by sbarman-mi9

- Description:  Added model name to `GPT4AllEmbeddings`. Apparently, when we use `CacheBackedEmbeddings`, we must provide a namespace so our doc embeddings with different model ids remain distinct. This change makes it easy to add name from the model.  
https://python.langchain.com/docs/modules/data_connection/caching_embeddings
  - Dependencies: None
  - Tag maintainer: @baskaryan

2023-08-19 22:21 UTC, baskaryan commented
the namespace in cached embeddings is optional, and can also be set directly (e.g. you can just pass in a string). if that's the only reason we're adding model here i'm not sure it's needed. 

cc @eyurtsev

2023-08-20 00:36 UTC, sbarman-mi9 commented
The cachedembedding is just an example. 

The model class should have a model identifier attribute. It's available for OpenAIEmbeddings, EmbaasEmbeddings, VertexAIEmbeddings, and others.  
1. Why GPT4AllEmbeddings should not have it as well?
3. If the user wants to know the default model being used, is there any attribute they can refer to model class (without private attributes)? 

I have also observed inconsistent naming. For instance, VertexAIEmbeddings is using `model_name` while OpenAIEmbeddings is using `model`.

2023-08-21 14:11 UTC, eyurtsev requested changes
@sbarman-mi9 thanks for the contribution! I'll discuss with @baskaryan whether a model name should be added to the base abstraction as an optional. 

We should not add `model` attribute to GPT4ALlEmbeddings on its own. Either it should be standardized across all models or else only added to models that leverage it (e.g., specifying it as part of an API request).

2023-08-21 23:36 UTC, sbarman-mi9 commented
Yup, adding it as base abstration would also work. Somethng we can identify the default model being used.

2023-09-21 22:10 UTC, leo-gan commented
@sbarman-mi9 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

2023-10-30 14:47 UTC, eyurtsev commented
Closing this PR for now since we don't want to introduce this attribute on this particular model

2023-10-30 14:47 UTC, closed without merging