Add del vector pgvector + adding modification time to confluence and google drive docs
langchain-ai/langchain pull request #9604
Opened 2023-08-22 12:06 UTC by NaamaMagami

Description:
- adding implementation of delete for pgvector
- adding modification time in docs metadata for confluence and google drive.

Issue:
https://github.com/langchain-ai/langchain/issues/9312

Tag maintainer: @baskaryan, @eyurtsev, @hwchase17, @rlancemartin.

2023-08-23 17:41 UTC, eyurtsev requested changes
Looks great! One change is to the `delete` method. The `ids` need to correspond to the same ids that the user passes in add_documents

2023-08-23 17:41 UTC, eyurtsev commented on libs/langchain/langchain/vectorstores/pgvector.py
> +        ids: Optional[List[str]] = None,
`ids` should be used to delete `custom_id`  to be consistent with other vectorstores. the `id` is the user assigned id for the document

If we want the ability to delete by `uuid`, we can rename `custom_ids` to `uuids` and have it delete by uuid

2023-08-24 15:45 UTC, eyurtsev approved these changes

2023-08-24 15:47 UTC, eyurtsev commented on libs/langchain/langchain/vectorstores/pgvector.py
> +        ids: Optional[List[str]] = None,
Thanks! I'm merging and going to make a PR to make the deletion more efficient. Deletion can be made much faster, but using a single SQL request.

2023-08-24 15:48 UTC, eyurtsev commented on libs/langchain/langchain/document_loaders/confluence.py
> +            metadata["when"] = page["version"]["when"]
might be better to call it more precisely: `when` -> `updated_at` / `last_modified_at`

to differentiate between update time from creation time

2023-08-25 03:48 UTC, eyurtsev commented
@baskaryan feel free to merge whenever

2023-08-25 04:09 UTC, merged

2023-08-25 13:24 UTC, NaamaMagami commented
hey, sorry for the delay - no problem, I'm not even sure it's possible to delete by uuid but I thought that maybe some users could use this functionality since the custom_id is not a unique id..
Thanks!